/**
 * lib/api/response.ts
 *
 * Canonical JSON response factories for all API route handlers.
 *
 * Every response carries:
 *   - Content-Type: application/json; charset=utf-8
 *   - X-Request-Id: <requestId>  (empty string when not provided)
 *   - timestamp: ISO-8601 server clock at response construction time
 *
 * Usage:
 *   return successResponse({ id, score }, undefined, 201, requestId);
 *   return errorResponse("NOT_FOUND", "Challenge not found.", undefined, 404, requestId);
 */

import { NextResponse } from "next/server";

const CONTENT_TYPE = "application/json; charset=utf-8";

// ---------------------------------------------------------------------------
// successResponse
// ---------------------------------------------------------------------------

/**
 * Creates a 2xx JSON response with a normalised envelope.
 *
 * @param data      The primary payload to return to the caller.
 * @param meta      Optional pagination cursor, counts, etc.
 * @param status    HTTP status code (default 200).
 * @param requestId UUID generated by withApiErrorHandler (for tracing).
 */
export function successResponse<T>(
  data: T,
  meta?: unknown,
  status = 200,
  requestId = "",
): NextResponse {
  const body = JSON.stringify({
    success: true,
    data,
    ...(meta !== undefined ? { meta } : {}),
    timestamp: new Date().toISOString(),
  });

  return new NextResponse(body, {
    status,
    headers: {
      "Content-Type": CONTENT_TYPE,
      "X-Request-Id": requestId,
    },
  });
}

// ---------------------------------------------------------------------------
// errorResponse
// ---------------------------------------------------------------------------

/**
 * Creates an error JSON response with a normalised envelope.
 *
 * @param code      Machine-readable error code (e.g. "NOT_FOUND").
 * @param message   Human-readable message safe to expose to the client.
 * @param details   Optional extra payload (Zod issues, field hints…).
 * @param status    HTTP status code (default 500).
 * @param requestId UUID for correlating logs with the client request.
 */
export function errorResponse(
  code: string,
  message: string,
  details?: unknown,
  status = 500,
  requestId = "",
): NextResponse {
  const errorBody: Record<string, unknown> = { code, message };
  if (details !== undefined) {
    errorBody["details"] = details;
  }

  const body = JSON.stringify({
    success: false,
    error: errorBody,
    timestamp: new Date().toISOString(),
  });

  return new NextResponse(body, {
    status,
    headers: {
      "Content-Type": CONTENT_TYPE,
      "X-Request-Id": requestId,
    },
  });
}
