"use client";

interface WeeklyReportData {
  week_start: Date | string;
  week_end: Date | string;
  ai_summary: string;
  ai_strengths: string;
  ai_gaps: string;
  ai_recommendation: string;
}

interface WeeklyCoachReportProps {
  report: WeeklyReportData | null;
}

export default function WeeklyCoachReport({ report }: WeeklyCoachReportProps) {
  // Якщо тижневого звіту ще немає в базі даних — показуємо плейсхолдер [E6]
  if (!report) {
    return (
      <div className="bg-zinc-900 border border-zinc-800 p-8 rounded-xl text-center space-y-2">
        <p className="text-sm text-zinc-400">
          Your first weekly report will appear after your first full week of
          practice.
        </p>
      </div>
    );
  }

  // Розрахунок красивого діапазону дат (наприклад, Jun 9 – Jun 15) [E6]
  const formatDateRange = (start: Date | string, end: Date | string) => {
    const s = new Date(start).toLocaleDateString("en-US", {
      month: "short",
      day: "numeric",
    });
    const e = new Date(end).toLocaleDateString("en-US", {
      month: "short",
      day: "numeric",
    });
    return `${s} – ${e}`;
  };

  return (
    <div className="bg-zinc-900 border border-zinc-800 rounded-xl p-8 space-y-6 shadow-2xl relative overflow-hidden">
      {/* Header [E6] */}
      <div className="flex items-center justify-between border-b border-zinc-800 pb-4">
        <div>
          <h2 className="text-xl font-bold tracking-tight text-zinc-100">
            AI Weekly Report
          </h2>
          <p className="text-xs text-zinc-500 mt-1">
            {formatDateRange(report.week_start, report.week_end)}
          </p>
        </div>
        <span className="text-xs bg-emerald-950/40 border border-emerald-800/50 text-emerald-400 px-2.5 py-1 rounded-full font-bold uppercase tracking-wider">
          Weekly Analysis
        </span>
      </div>

      {/* 4 Секції з іконками та лівими кольоровими бордерами [E6] */}
      <div className="space-y-6">
        {/* 1. Summary */}
        <div className="space-y-2">
          <h3 className="text-xs font-bold text-zinc-500 uppercase tracking-wider flex items-center space-x-1.5">
            <span>📝</span> <span>Summary</span>
          </h3>
          <p className="text-sm text-zinc-300 leading-relaxed italic">
            "{report.ai_summary}"
          </p>
        </div>

        {/* 2. Strengths [E6] */}
        <div className="space-y-2 border-l-2 border-emerald-500 pl-4">
          <h3 className="text-xs font-bold text-emerald-500 uppercase tracking-wider flex items-center space-x-1.5">
            <span>🥇</span> <span>Strengths</span>
          </h3>
          <p className="text-sm text-zinc-300 leading-relaxed">
            {report.ai_strengths}
          </p>
        </div>

        {/* 3. Gaps [E6] */}
        <div className="space-y-2 border-l-2 border-amber-500 pl-4">
          <h3 className="text-xs font-bold text-amber-500 uppercase tracking-wider flex items-center space-x-1.5">
            <span>⚠️</span> <span>Gaps</span>
          </h3>
          <p className="text-sm text-zinc-300 leading-relaxed">
            {report.ai_gaps}
          </p>
        </div>

        {/* 4. Recommendation (This week's focus) [E6] */}
        <div className="space-y-2 border-l-2 border-purple-500 pl-4">
          <h3 className="text-xs font-bold text-purple-500 uppercase tracking-wider flex items-center space-x-1.5">
            <span>🎯</span> <span>This week's focus</span>
          </h3>
          <p className="text-sm font-bold text-zinc-100 leading-relaxed">
            {report.ai_recommendation}
          </p>
        </div>
      </div>

      {/* Footer [E6] */}
      <div className="border-t border-zinc-800 pt-4 flex justify-between items-center text-[10px] text-zinc-500">
        <span>ProofLoom AI Coach</span>
        <span>Generated by Amazon Bedrock Nova Lite</span>
      </div>
    </div>
  );
}
